vieille_sardine_produit_homepage:
    pattern:  /produit
    defaults: { _controller: VieilleSardineProduitBundle:Produit:index }
    
vieille_sardine_produit_ajout:
    pattern:  /ajout
    defaults: { _controller: VieilleSardineProduitBundle:Produit:ajout }
